name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
      - name: Run Cypress tests
        run: npm run cypress:run || true
      - name: Print failure message if tests fail
        run: |
         if [ $? -ne 0 ]; then
         echo "Some tests failed! Please check the Cypress test logs for details."
         fi

